### ISSUE TITLE
Can not find header.html

### ISSUE THREAD

**Issue by Schievel1** [cfclrk/markdown-xwidget#10]
Whenever I run `M-x markdown-xwidget-preview-mode` I only get 
`Opening input file: No such file or directory, /home/pascal/.config/emacs/.local/straight/build-29.1/markdown-xwidget/resources/header.html`

I am runnig emacs 29.1-r6 with Doom. 
I installed markdown-xwidget with Doom straight package manager, if that matters. 
I can use xwidgets fine with `xwidget-webkit-browse-url`
I have `markdown-xwidget-command` set to pandoc and pandoc is installed (3.1.9)

Do I need to do anything else? I thought markdown-xwidget is going to generate that html page by itself.

**Comment by Schievel1** [comment]
Nevermind, problem is in front of keyboard. 
For the record, when using Dooms package macro, one has to specify the files as well (as you also do it in the example in your README)
```
(package! markdown-xwidget
  :recipe (:host github :repo "cfclrk/markdown-xwidget" :files (:defaults "resources")))
```

**Comment by cfclrk** [comment]
Hey, someone is using my package 💜!

Thanks for posting the solution. I added to the readme: https://github.com/cfclrk/markdown-xwidget#doom

It would be even easier to install if I put this on MELPA. I'll try to do that soon.
